// Contenido de la página /docs — comandos reales del CLI (`randi --help`).
export const cmdEs: Array<[string, string]> = [
  ['randi', 'Menú interactivo'],
  ['randi chat [modelo]', 'Chat TUI (terminal)'],
  ['randi run [modelo]', 'Ejecuta un modelo directamente'],
  ['randi serve', 'Inicia el servidor Ollama'],
  ['randi stop', 'Detiene el servidor Ollama'],
  ['randi pull [modelo]', 'Descarga uno o varios modelos'],
  ['randi list', 'Lista modelos instalados'],
  ['randi ps', 'Modelos cargados en memoria'],
  ['randi models', 'Catálogo recomendado'],
  ['randi status', 'Estado del sistema'],
  ['randi config', 'Ver la configuración'],
  ['randi update', 'Actualizar RANDI'],
  ['randi web [puerto]', 'Interfaz web local en el navegador'],
  ['randi img "prompt"', 'Generar imagen (A1111/GPU)'],
  ['randi doctor', 'Diagnóstico del sistema'],
  ['randi hardware', 'Detecta CPU/GPU/RAM/VRAM/ancho de banda'],
  ['randi recommend [uso]', 'Modelos recomendados para TU equipo'],
  ['randi tier', 'Tiers S-F de tu hardware'],
  ['randi compare a b', 'Compara dos modelos'],
  ['randi install <modelo>', 'Instala y configura un modelo'],
  ['randi setup', 'Onboarding por hardware'],
  ['randi requirements', 'Requisitos y dependencias'],
  ['randi ensure', 'Instala Python y Ollama (Windows nativo)'],
];

export const cmdEn: Array<[string, string]> = [
  ['randi', 'Interactive menu'],
  ['randi chat [model]', 'TUI chat (terminal)'],
  ['randi run [model]', 'Run a model directly'],
  ['randi serve', 'Start the Ollama server'],
  ['randi stop', 'Stop the Ollama server'],
  ['randi pull [model]', 'Download one or more models'],
  ['randi list', 'List installed models'],
  ['randi ps', 'Models loaded in memory'],
  ['randi models', 'Recommended catalog'],
  ['randi status', 'System status'],
  ['randi config', 'View configuration'],
  ['randi update', 'Update RANDI'],
  ['randi web [port]', 'Local web UI in your browser'],
  ['randi img "prompt"', 'Generate image (A1111/GPU)'],
  ['randi doctor', 'System diagnostics'],
  ['randi hardware', 'Detects CPU/GPU/RAM/VRAM/bandwidth'],
  ['randi recommend [usage]', 'Models recommended for YOUR device'],
  ['randi tier', 'S-F tiers for your hardware'],
  ['randi compare a b', 'Compare two models'],
  ['randi install <model>', 'Install and configure a model'],
  ['randi setup', 'Hardware onboarding'],
  ['randi requirements', 'Requirements and dependencies'],
  ['randi ensure', 'Install Python + Ollama (native Windows)'],
];